version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./emails_state.json:/app/emails_state.json
      - ./init_emails.json:/app/init_emails.json
